export enum Effect {
    strength = 'Strength',
    intellect = 'Intellect',
    agility = 'Agility',
    critical = 'Critical Strike',
    spirit = 'Spirit',
    haste = 'Haste',
    spellpower = 'Spell Power',
    attackpower = 'Attack Power',
    mp5 = 'Mp5',
    defense = 'Defense',
    block = 'Block',
    parry = 'Parry',
    dodge = 'Dodge',
    stamina = 'Stamina',
    spellpen = 'Spell Penetration',
    armpen = 'Armor Penetration',
    resilience = 'Resilience',
    expertise = 'Expertise',
    hit = 'Hit Rating',
  }
  
  export enum Color {
    red = 'Red',
    blue = 'Blue',
    yellow = 'Yellow',
    orange = 'Orange(Red/Yellow) ',
    purple = 'Purple(Red/Blue) ',
    green = 'Green(Blue/Yellow) ',
  }
  
  export enum Quality {
    uncommon = 'Uncommon ',
    perfect = 'Perfect Uncommon',
    rare = 'Rare',
    epic = 'Epic',
  }
  
  export type Stats = {
    value: string;
    effect: Effect;
  };
  
  export type GemData = {
    name: string;
    stats: Stats[];
    source: string;
    color: Color;
    quality: Quality;
  };
  
  export const gemsData: GemData[] = [
    {
      name: 'Delicate Bloodstone',
      stats: [{ value: '+12', effect: Effect.agility }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Runed Bloodstone',
      stats: [{ value: '+14', effect: Effect.spellpower }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Delicate Bloodstone',
      stats: [{ value: '+14', effect: Effect.agility }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Runed Bloodstone',
      stats: [{ value: '+16', effect: Effect.spellpower }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Delicate Scarlet Ruby',
      stats: [{ value: '+16', effect: Effect.agility }],
      source: 'Tiffany Cartier',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Runed Scarlet Ruby',
      stats: [{ value: '+19', effect: Effect.spellpower }],
      source: 'Kirin Tor',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Delicate Stormjewel',
      stats: [{ value: '+20', effect: Effect.agility }],
      source: 'Bag of Fishing Treasures',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Runed Stormjewel',
      stats: [{ value: '+23', effect: Effect.spellpower }],
      source: 'Bag of Fishing Treasures',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Delicate Cardinal Ruby',
      stats: [{ value: '+20', effect: Effect.agility }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Runed Cardinal Ruby',
      stats: [{ value: '+23', effect: Effect.spellpower }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Bold Bloodstone',
      stats: [{ value: '+12', effect: Effect.strength }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Precise Bloodstone',
      stats: [{ value: '+12', effect: Effect.expertise }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Bold Bloodstone',
      stats: [{ value: '+14', effect: Effect.strength }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Precise Bloodstone',
      stats: [{ value: '+14', effect: Effect.expertise }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Bold Scarlet Ruby',
      stats: [{ value: '+16', effect: Effect.strength }],
      source: 'Tiffany Cartier',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Precise Scarlet Ruby',
      stats: [{ value: '+16', effect: Effect.expertise }],
      source: 'Herald Volazj',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Bold Stormjewel',
      stats: [{ value: '+20', effect: Effect.strength }],
      source: 'Bag of Fishing Treasures',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Precise Cardinal Ruby',
      stats: [{ value: '+20', effect: Effect.expertise }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Bold Cardinal Ruby',
      stats: [{ value: '+20', effect: Effect.strength }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Bright Bloodstone',
      stats: [{ value: '+24', effect: Effect.attackpower }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Fractured Bloodstone',
      stats: [{ value: '+12', effect: Effect.armpen }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Bright Bloodstone',
      stats: [{ value: '+26', effect: Effect.attackpower }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Fractured Bloodstone',
      stats: [{ value: '+14', effect: Effect.armpen }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Bright Scarlet Ruby',
      stats: [{ value: '+32', effect: Effect.attackpower }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Fractured Scarlet Ruby',
      stats: [{ value: '+16', effect: Effect.armpen }],
      source: "Nascent Val'kyr",
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Bright Cardinal Ruby',
      stats: [{ value: '+40', effect: Effect.attackpower }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Fractured Cardinal Ruby',
      stats: [{ value: '+20', effect: Effect.armpen }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Subtle Bloodstone',
      stats: [{ value: '+12', effect: Effect.dodge }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Flashing Bloodstone',
      stats: [{ value: '+12', effect: Effect.parry }],
      source: 'Trainer',
      color: Color.red,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Subtle Bloodstone',
      stats: [{ value: '+14', effect: Effect.dodge }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Flashing Bloodstone',
      stats: [{ value: '+14', effect: Effect.parry }],
      source: 'Gem Perfection',
      color: Color.red,
      quality: Quality.perfect,
    },
    {
      name: 'Subtle Scarlet Ruby',
      stats: [{ value: '+16', effect: Effect.dodge }],
      source: 'Tiffany Cartier',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Flashing Scarlet Ruby',
      stats: [{ value: '+16', effect: Effect.parry }],
      source: 'Tiffany Cartier',
      color: Color.red,
      quality: Quality.rare,
    },
    {
      name: 'Subtle Cardinal Ruby',
      stats: [{ value: '+20', effect: Effect.dodge }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Flashing Cardinal Ruby',
      stats: [{ value: '+20', effect: Effect.parry }],
      source: 'Timothy Jones',
      color: Color.red,
      quality: Quality.epic,
    },
    {
      name: 'Quick Sun Crystal',
      stats: [{ value: '+12', effect: Effect.haste }],
      source: 'Trainer',
      color: Color.yellow,
      quality: Quality.uncommon,
    },
    {
      name: 'Smooth Sun Crystal',
      stats: [{ value: '+12', effect: Effect.critical }],
      source: 'Trainer',
      color: Color.yellow,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Quick Sun Crystal',
      stats: [{ value: '+14', effect: Effect.haste }],
      source: 'Gem Perfection',
      color: Color.yellow,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Smooth Sun Crystal',
      stats: [{ value: '+14', effect: Effect.critical }],
      source: 'Gem Perfection',
      color: Color.yellow,
      quality: Quality.perfect,
    },
    {
      name: "Quick Autumn's Glow",
      stats: [{ value: '+16', effect: Effect.haste }],
      source: 'Tiffany Cartier',
      color: Color.yellow,
      quality: Quality.rare,
    },
    {
      name: "Smooth Autumn's Glow",
      stats: [{ value: '+16', effect: Effect.critical }],
      source: 'Sons of Hodir',
      color: Color.yellow,
      quality: Quality.rare,
    },
    {
      name: "Quick King's Amber",
      stats: [{ value: '+20', effect: Effect.haste }],
      source: 'Timothy Jones',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: "Smooth King's Amber",
      stats: [{ value: '+20', effect: Effect.critical }],
      source: 'Timothy Jones',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: 'Brilliant Sun Crystal',
      stats: [{ value: '+12', effect: Effect.intellect }],
      source: 'Trainer',
      color: Color.yellow,
      quality: Quality.uncommon,
    },
    {
      name: 'Thick Sun Crystal',
      stats: [{ value: '+12', effect: Effect.defense }],
      source: 'Trainer',
      color: Color.yellow,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Brilliant Sun Crystal',
      stats: [{ value: '+14', effect: Effect.intellect }],
      source: 'Gem Perfection',
      color: Color.yellow,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Thick Sun Crystal',
      stats: [{ value: '+14', effect: Effect.defense }],
      source: 'Gem Perfection',
      color: Color.yellow,
      quality: Quality.perfect,
    },
    {
      name: "Brilliant Autumn's Glow",
      stats: [{ value: '+16', effect: Effect.intellect }],
      source: 'Trainer',
      color: Color.yellow,
      quality: Quality.rare,
    },
    {
      name: "Thick Autumn's Glow",
      stats: [{ value: '+16', effect: Effect.defense }],
      source: 'Cyanigosa',
      color: Color.yellow,
      quality: Quality.rare,
    },
    {
      name: 'Brilliant Stormjewel',
      stats: [{ value: '+20', effect: Effect.intellect }],
      source: 'Bag of Fishing Treasures',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: "Thick King's Amber",
      stats: [{ value: '+20', effect: Effect.defense }],
      source: 'Timothy Jones',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: "Brilliant King's Amber",
      stats: [{ value: '+20', effect: Effect.intellect }],
      source: 'Timothy Jones',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: 'Mystic Sun Crystal',
      stats: [{ value: '+12', effect: Effect.resilience }],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.yellow,
      quality: Quality.uncommon,
    },
    {
      name: 'Rigid Sun Crystal',
      stats: [{ value: '+12', effect: Effect.hit }],
      source: 'Trainer',
      color: Color.yellow,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Mystic Sun Crystal',
      stats: [{ value: '+14', effect: Effect.resilience }],
      source: 'Gem Perfection',
      color: Color.yellow,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Rigid Sun Crystal',
      stats: [{ value: '+14', effect: Effect.hit }],
      source: 'Gem Perfection',
      color: Color.yellow,
      quality: Quality.perfect,
    },
    {
      name: "Mystic Autumn's Glow",
      stats: [{ value: '+16', effect: Effect.resilience }],
      source: 'Wintergrasp',
      color: Color.yellow,
      quality: Quality.rare,
    },
    {
      name: "Rigid Autumn's Glow",
      stats: [{ value: '+16', effect: Effect.hit }],
      source: 'Tiffany Cartier',
      color: Color.yellow,
      quality: Quality.rare,
    },
    {
      name: "Kharmaa's Grace",
      stats: [{ value: '+20', effect: Effect.resilience }],
      source: 'Wintergrasp',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: 'Rigid Stormjewel',
      stats: [{ value: '+20', effect: Effect.hit }],
      source: 'Bag of Fishing Treasures',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: "Mystic King's Amber",
      stats: [{ value: '+20', effect: Effect.resilience }],
      source: 'Timothy Jones',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: "Rigid King's Amber",
      stats: [{ value: '+20', effect: Effect.hit }],
      source: 'Timothy Jones',
      color: Color.yellow,
      quality: Quality.epic,
    },
    {
      name: 'Solid Chalcedony',
      stats: [{ value: '+18', effect: Effect.stamina }],
      source: 'Trainer',
      color: Color.blue,
      quality: Quality.uncommon,
    },
    {
      name: 'Sparkling Chalcedony',
      stats: [{ value: '+12', effect: Effect.spirit }],
      source: 'Trainer',
      color: Color.blue,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Solid Chalcedony',
      stats: [{ value: '+21', effect: Effect.stamina }],
      source: 'Gem Perfection',
      color: Color.blue,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Sparkling Chalcedony',
      stats: [{ value: '+14', effect: Effect.spirit }],
      source: 'Gem Perfection',
      color: Color.blue,
      quality: Quality.perfect,
    },
    {
      name: 'Solid Sky Sapphire',
      stats: [{ value: '+24', effect: Effect.stamina }],
      source: 'Tiffany Cartier',
      color: Color.blue,
      quality: Quality.rare,
    },
    {
      name: 'Sparkling Sky Sapphire',
      stats: [{ value: '+16', effect: Effect.spirit }],
      source: 'Trainer',
      color: Color.blue,
      quality: Quality.rare,
    },
    {
      name: 'Solid Stormjewel',
      stats: [{ value: '+30', effect: Effect.stamina }],
      source: 'Bag of Fishing Treasures',
      color: Color.blue,
      quality: Quality.epic,
    },
    {
      name: 'Sparkling Stormjewel',
      stats: [{ value: '+20', effect: Effect.spirit }],
      source: 'Bag of Fishing Treasures',
      color: Color.blue,
      quality: Quality.epic,
    },
    {
      name: 'Solid Majestic Zircon',
      stats: [{ value: '+30', effect: Effect.stamina }],
      source: 'Timothy Jones',
      color: Color.blue,
      quality: Quality.epic,
    },
    {
      name: 'Sparkling Majestic Zircon',
      stats: [{ value: '+20', effect: Effect.spirit }],
      source: 'Timothy Jones',
      color: Color.blue,
      quality: Quality.epic,
    },
    {
      name: 'Lustrous Chalcedony',
      stats: [{ value: '+6', effect: Effect.mp5 }],
      source: 'Trainer',
      color: Color.blue,
      quality: Quality.uncommon,
    },
    {
      name: 'Stormy Chalcedony',
      stats: [{ value: '+15', effect: Effect.spellpen }],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.blue,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Lustrous Chalcedony',
      stats: [{ value: '+7', effect: Effect.mp5 }],
      source: 'Gem Perfection',
      color: Color.blue,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Stormy Chalcedony',
      stats: [{ value: '+18', effect: Effect.spellpen }],
      source: 'Gem Perfection',
      color: Color.blue,
      quality: Quality.perfect,
    },
    {
      name: 'Lustrous Sky Sapphire',
      stats: [{ value: '+8', effect: Effect.mp5 }],
      source: 'Tiffany Cartier',
      color: Color.blue,
      quality: Quality.rare,
    },
    {
      name: 'Stormy Sky Sapphire',
      stats: [{ value: '+20', effect: Effect.spellpen }],
      source: 'Wintergrasp',
      color: Color.blue,
      quality: Quality.rare,
    },
    {
      name: 'Lustrous Majestic Zircon',
      stats: [{ value: '+10', effect: Effect.mp5 }],
      source: 'Timothy Jones',
      color: Color.blue,
      quality: Quality.epic,
    },
    {
      name: 'Stormy Majestic Zircon',
      stats: [{ value: '+25', effect: Effect.spellpen }],
      source: 'Timothy Jones',
      color: Color.blue,
      quality: Quality.epic,
    },
    {
      name: 'Durable Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+6', effect: Effect.resilience },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Stark Huge Citrine',
      stats: [
        { value: '+12', effect: Effect.attackpower },
        { value: '+6', effect: Effect.haste },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Durable Huge Citrine',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+7', effect: Effect.resilience },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Stark Huge Citrine',
      stats: [
        { value: '+14', effect: Effect.attackpower },
        { value: '+7', effect: Effect.haste },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Durable Monarch Topaz',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+8', effect: Effect.resilience },
      ],
      source: 'Wintergrasp',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Stark Monarch Topaz',
      stats: [
        { value: '+16', effect: Effect.attackpower },
        { value: '+8', effect: Effect.haste },
      ],
      source: 'Tiffany Cartier',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Durable Ametrine',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+10', effect: Effect.resilience },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Stark Ametrine',
      stats: [
        { value: '+20', effect: Effect.attackpower },
        { value: '+10', effect: Effect.haste },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Luminous Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+6', effect: Effect.intellect },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Pristine Huge Citrine',
      stats: [
        { value: '+12', effect: Effect.attackpower },
        { value: '+6', effect: Effect.hit },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Luminous Huge Citrine',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+7', effect: Effect.intellect },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Pristine Huge Citrine',
      stats: [
        { value: '+14', effect: Effect.attackpower },
        { value: '+7', effect: Effect.hit },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Luminous Monarch Topaz',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+8', effect: Effect.intellect },
      ],
      source: 'Tiffany Cartier',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Pristine Monarch Topaz',
      stats: [
        { value: '+16', effect: Effect.attackpower },
        { value: '+8', effect: Effect.hit },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Luminous Ametrine',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+10', effect: Effect.intellect },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Pristine Ametrine',
      stats: [
        { value: '+20', effect: Effect.attackpower },
        { value: '+10', effect: Effect.hit },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Potent Huge Citrine',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+7', effect: Effect.critical },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Wicked Huge Citrine',
      stats: [
        { value: '+12', effect: Effect.attackpower },
        { value: '+6', effect: Effect.critical },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Potent Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+6', effect: Effect.critical },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Wicked Huge Citrine',
      stats: [
        { value: '+14', effect: Effect.attackpower },
        { value: '+7', effect: Effect.critical },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Potent Monarch Topaz',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+8', effect: Effect.critical },
      ],
      source: 'Tiffany Cartier',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Wicked Monarch Topaz',
      stats: [
        { value: '+16', effect: Effect.attackpower },
        { value: '+8', effect: Effect.critical },
      ],
      source: 'Knights of the Ebon Blade',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Potent Ametrine',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+10', effect: Effect.critical },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Wicked Ametrine',
      stats: [
        { value: '+20', effect: Effect.attackpower },
        { value: '+10', effect: Effect.critical },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Veiled Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+6', effect: Effect.hit },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Empowered Huge Citrine',
      stats: [
        { value: '+12', effect: Effect.attackpower },
        { value: '+6', effect: Effect.resilience },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Veiled Huge Citrine',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+7', effect: Effect.hit },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Empowered Huge Citrine',
      stats: [
        { value: '+14', effect: Effect.attackpower },
        { value: '+7', effect: Effect.resilience },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Veiled Monarch Topaz',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+8', effect: Effect.hit },
      ],
      source: 'Tiffany Cartier',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Empowered Monarch Topaz',
      stats: [
        { value: '+16', effect: Effect.attackpower },
        { value: '+8', effect: Effect.resilience },
      ],
      source: 'Wintergrasp',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Veiled Ametrine',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+10', effect: Effect.hit },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Empowered Ametrine',
      stats: [
        { value: '+20', effect: Effect.attackpower },
        { value: '+10', effect: Effect.resilience },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Reckless Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+6', effect: Effect.haste },
      ],
      source: 'Frenzyheart',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Deft Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.agility },
        { value: '+6', effect: Effect.haste },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Reckless Huge Citrine',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+7', effect: Effect.haste },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Deft Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.agility },
        { value: '+7', effect: Effect.haste },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Reckless Monarch Topaz',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+8', effect: Effect.haste },
      ],
      source: 'Tiffany Cartier',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Deft Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.agility },
        { value: '+8', effect: Effect.haste },
      ],
      source: 'Sjonnir the Ironshaper',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Reckless Ametrine',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+10', effect: Effect.haste },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Deft Ametrine',
      stats: [
        { value: '+10', effect: Effect.agility },
        { value: '+10', effect: Effect.haste },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Inscribed Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.strength },
        { value: '+6', effect: Effect.critical },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Glinting Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.agility },
        { value: '+6', effect: Effect.hit },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Inscribed Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.strength },
        { value: '+7', effect: Effect.critical },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Glinting Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.agility },
        { value: '+7', effect: Effect.hit },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Inscribed Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.strength },
        { value: '+8', effect: Effect.critical },
      ],
      source: 'World Drop',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Glinting Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.agility },
        { value: '+8', effect: Effect.hit },
      ],
      source: 'Tiffany Cartier',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Inscribed Ametrine',
      stats: [
        { value: '+10', effect: Effect.strength },
        { value: '+10', effect: Effect.critical },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Glinting Ametrine',
      stats: [
        { value: '+10', effect: Effect.agility },
        { value: '+10', effect: Effect.hit },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Etched Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.strength },
        { value: '+6', effect: Effect.hit },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Deadly Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.agility },
        { value: '+6', effect: Effect.critical },
      ],
      source: 'Knights of the Ebon Blade',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Etched Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.strength },
        { value: '+7', effect: Effect.hit },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Deadly Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.agility },
        { value: '+7', effect: Effect.critical },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Etched Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.strength },
        { value: '+8', effect: Effect.hit },
      ],
      source: 'World Drop',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Deadly Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.agility },
        { value: '+8', effect: Effect.critical },
      ],
      source: 'Keristrasza',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Etched Ametrine',
      stats: [
        { value: '+10', effect: Effect.strength },
        { value: '+10', effect: Effect.hit },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Deadly Ametrine',
      stats: [
        { value: '+10', effect: Effect.agility },
        { value: '+10', effect: Effect.critical },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Fierce Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.strength },
        { value: '+6', effect: Effect.haste },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Lucent Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.agility },
        { value: '+6', effect: Effect.resilience },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Fierce Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.strength },
        { value: '+7', effect: Effect.haste },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Lucent Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.agility },
        { value: '+7', effect: Effect.resilience },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Fierce Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.strength },
        { value: '+8', effect: Effect.haste },
      ],
      source: 'Ingvar the Plunderer',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Lucent Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.agility },
        { value: '+8', effect: Effect.resilience },
      ],
      source: 'Wintergrasp',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Fierce Ametrine',
      stats: [
        { value: '+10', effect: Effect.strength },
        { value: '+10', effect: Effect.haste },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Lucent Ametrine',
      stats: [
        { value: '+10', effect: Effect.agility },
        { value: '+10', effect: Effect.resilience },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Resplendent Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.strength },
        { value: '+6', effect: Effect.resilience },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Stalwart Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.dodge },
        { value: '+6', effect: Effect.defense },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Resplendent Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.strength },
        { value: '+7', effect: Effect.resilience },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Stalwart Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.dodge },
        { value: '+7', effect: Effect.defense },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Resplendent Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.strength },
        { value: '+8', effect: Effect.resilience },
      ],
      source: 'Wintergrasp',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Stalwart Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.dodge },
        { value: '+8', effect: Effect.defense },
      ],
      source: 'World Drop',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Resplendent Ametrine',
      stats: [
        { value: '+10', effect: Effect.strength },
        { value: '+10', effect: Effect.resilience },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Stalwart Ametrine',
      stats: [
        { value: '+10', effect: Effect.dodge },
        { value: '+10', effect: Effect.defense },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: "Champion's Huge Citrine",
      stats: [
        { value: '+6', effect: Effect.strength },
        { value: '+6', effect: Effect.defense },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Glimmering Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.parry },
        { value: '+6', effect: Effect.defense },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: "Perfect Champion's Huge Citrine",
      stats: [
        { value: '+7', effect: Effect.strength },
        { value: '+7', effect: Effect.defense },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Glimmering Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.parry },
        { value: '+7', effect: Effect.defense },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: "Champion's Monarch Topaz",
      stats: [
        { value: '+8', effect: Effect.strength },
        { value: '+8', effect: Effect.defense },
      ],
      source: 'World Drop',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Glimmering Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.parry },
        { value: '+8', effect: Effect.defense },
      ],
      source: 'Wyrmrest Accord',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: "Champion's Ametrine",
      stats: [
        { value: '+10', effect: Effect.strength },
        { value: '+10', effect: Effect.defense },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Glimmering Ametrine',
      stats: [
        { value: '+10', effect: Effect.parry },
        { value: '+10', effect: Effect.defense },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Accurate Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.expertise },
        { value: '+6', effect: Effect.hit },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Resolute Huge Citrine',
      stats: [
        { value: '+6', effect: Effect.expertise },
        { value: '+6', effect: Effect.defense },
      ],
      source: 'Trainer',
      color: Color.orange,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Accurate Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.expertise },
        { value: '+7', effect: Effect.hit },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Resolute Huge Citrine',
      stats: [
        { value: '+7', effect: Effect.expertise },
        { value: '+7', effect: Effect.defense },
      ],
      source: 'Gem Perfection',
      color: Color.orange,
      quality: Quality.perfect,
    },
    {
      name: 'Accurate Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.expertise },
        { value: '+8', effect: Effect.hit },
      ],
      source: 'Storm Peaks mammoths',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Resolute Monarch Topaz',
      stats: [
        { value: '+8', effect: Effect.expertise },
        { value: '+8', effect: Effect.defense },
      ],
      source: 'World Drop',
      color: Color.orange,
      quality: Quality.rare,
    },
    {
      name: 'Accurate Ametrine',
      stats: [
        { value: '+10', effect: Effect.expertise },
        { value: '+10', effect: Effect.hit },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Resolute Ametrine',
      stats: [
        { value: '+10', effect: Effect.expertise },
        { value: '+10', effect: Effect.defense },
      ],
      source: 'Timothy Jones',
      color: Color.orange,
      quality: Quality.epic,
    },
    {
      name: 'Jagged Dark Jade',
      stats: [
        { value: '+6', effect: Effect.critical },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Opaque Dark Jade',
      stats: [
        { value: '+6', effect: Effect.resilience },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Jagged Dark Jade',
      stats: [
        { value: '+7', effect: Effect.critical },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Opaque Dark Jade',
      stats: [
        { value: '+7', effect: Effect.resilience },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Jagged Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.critical },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Frenzyheart',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Opaque Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.resilience },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Wintergrasp',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Jagged Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.critical },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Opaque Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.resilience },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Dazzling Dark Jade',
      stats: [
        { value: '+6', effect: Effect.intellect },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Forceful Dark Jade',
      stats: [
        { value: '+7', effect: Effect.haste },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Dazzling Dark Jade',
      stats: [
        { value: '+7', effect: Effect.intellect },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Forceful Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.haste },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Dazzling Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.intellect },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Forceful Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.haste },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Dazzling Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.intellect },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Enduring Dark Jade',
      stats: [
        { value: '+6', effect: Effect.defense },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Sundered Dark Jade',
      stats: [
        { value: '+6', effect: Effect.critical },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Enduring Dark Jade',
      stats: [
        { value: '+7', effect: Effect.defense },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Sundered Dark Jade',
      stats: [
        { value: '+7', effect: Effect.critical },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Enduring Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.defense },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Sundered Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.critical },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Oracles',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Enduring Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.defense },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Sundered Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.critical },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Timeless Dark Jade',
      stats: [
        { value: '+6', effect: Effect.intellect },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Lambent Dark Jade',
      stats: [
        { value: '+6', effect: Effect.hit },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Timeless Dark Jade',
      stats: [
        { value: '+7', effect: Effect.intellect },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Lambent Dark Jade',
      stats: [
        { value: '+7', effect: Effect.hit },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Timeless Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.intellect },
        { value: '+12', effect: Effect.stamina },
      ],
      source: "The Prophet Tharon'ja",
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Lambent Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.hit },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Timeless Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.intellect },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Lambent Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.hit },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Vivid Dark Jade',
      stats: [
        { value: '+6', effect: Effect.hit },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Oracles',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Energized Dark Jade',
      stats: [
        { value: '+6', effect: Effect.haste },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Vivid Dark Jade',
      stats: [
        { value: '+7', effect: Effect.hit },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Energized Dark Jade',
      stats: [
        { value: '+7', effect: Effect.haste },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Vivid Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.hit },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Energized Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.haste },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Vivid Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.hit },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Energized Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.haste },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Steady Dark Jade',
      stats: [
        { value: '+6', effect: Effect.resilience },
        { value: '+9', effect: Effect.stamina },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Intricate Dark Jade',
      stats: [
        { value: '+6', effect: Effect.haste },
        { value: '+6', effect: Effect.spirit },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Steady Dark Jade',
      stats: [
        { value: '+7', effect: Effect.resilience },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Intricate Dark Jade',
      stats: [
        { value: '+7', effect: Effect.haste },
        { value: '+6', effect: Effect.spirit },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Steady Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.resilience },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Wintergrasp',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Intricate Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.haste },
        { value: '+8', effect: Effect.spirit },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Steady Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.resilience },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Intricate Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.haste },
        { value: '+10', effect: Effect.spirit },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Radiant Dark Jade',
      stats: [
        { value: '+6', effect: Effect.critical },
        { value: '+8', effect: Effect.spellpen },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: "Seer's Dark Jade",
      stats: [
        { value: '+6', effect: Effect.intellect },
        { value: '+6', effect: Effect.spirit },
      ],
      source: "Kalu'ak",
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Radiant Dark Jade',
      stats: [
        { value: '+7', effect: Effect.critical },
        { value: '+9', effect: Effect.spellpen },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: "Perfect Seer's Dark Jade",
      stats: [
        { value: '+7', effect: Effect.intellect },
        { value: '+7', effect: Effect.spirit },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Radiant Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.critical },
        { value: '+10', effect: Effect.spellpen },
      ],
      source: 'Storm Peaks harpies',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: "Seer's Forest Emerald",
      stats: [
        { value: '+8', effect: Effect.intellect },
        { value: '+8', effect: Effect.spirit },
      ],
      source: 'Tiffany Cartier',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Radiant Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.critical },
        { value: '+13', effect: Effect.spellpen },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: "Seer's Eye of Zul",
      stats: [
        { value: '+10', effect: Effect.intellect },
        { value: '+10', effect: Effect.spirit },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Tense Dark Jade',
      stats: [
        { value: '+6', effect: Effect.hit },
        { value: '+8', effect: Effect.spellpen },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Shining Dark Jade',
      stats: [
        { value: '+6', effect: Effect.hit },
        { value: '+6', effect: Effect.spirit },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Tense Dark Jade',
      stats: [
        { value: '+6', effect: Effect.hit },
        { value: '+9', effect: Effect.spellpen },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Shining Dark Jade',
      stats: [
        { value: '+7', effect: Effect.hit },
        { value: '+7', effect: Effect.spirit },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Tense Forest Emerald',
      stats: [
        { value: '+6', effect: Effect.hit },
        { value: '+10', effect: Effect.spellpen },
      ],
      source: 'Wintergrasp',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Shining Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.hit },
        { value: '+8', effect: Effect.spirit },
      ],
      source: 'World Drop',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Tense Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.hit },
        { value: '+13', effect: Effect.spellpen },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Shining Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.hit },
        { value: '+10', effect: Effect.spirit },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Shattered Dark Jade',
      stats: [
        { value: '+6', effect: Effect.haste },
        { value: '+8', effect: Effect.spellpen },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Misty Dark Jade',
      stats: [
        { value: '+6', effect: Effect.critical },
        { value: '+6', effect: Effect.spirit },
      ],
      source: 'Trainer',
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Shattered Dark Jade',
      stats: [
        { value: '+7', effect: Effect.haste },
        { value: '+9', effect: Effect.spellpen },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Misty Dark Jade',
      stats: [
        { value: '+7', effect: Effect.critical },
        { value: '+7', effect: Effect.spirit },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Shattered Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.haste },
        { value: '+10', effect: Effect.spellpen },
      ],
      source: 'Wintergrasp',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Misty Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.critical },
        { value: '+8', effect: Effect.spirit },
      ],
      source: 'World Drop',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Shattered Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.haste },
        { value: '+13', effect: Effect.spellpen },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Misty Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.critical },
        { value: '+10', effect: Effect.spirit },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Turbid Dark Jade',
      stats: [
        { value: '+6', effect: Effect.resilience },
        { value: '+6', effect: Effect.spirit },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.green,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Turbid Dark Jade',
      stats: [
        { value: '+7', effect: Effect.resilience },
        { value: '+7', effect: Effect.spirit },
      ],
      source: 'Gem Perfection',
      color: Color.green,
      quality: Quality.perfect,
    },
    {
      name: 'Turbid Forest Emerald',
      stats: [
        { value: '+8', effect: Effect.resilience },
        { value: '+8', effect: Effect.spirit },
      ],
      source: 'Wintergrasp',
      color: Color.green,
      quality: Quality.rare,
    },
    {
      name: 'Turbid Eye of Zul',
      stats: [
        { value: '+10', effect: Effect.resilience },
        { value: '+10', effect: Effect.spirit },
      ],
      source: 'Timothy Jones',
      color: Color.green,
      quality: Quality.epic,
    },
    {
      name: 'Sovereign Shadow Crystal',
      stats: [
        { value: '+6', effect: Effect.strength },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Shifting Shadow Crystal',
      stats: [
        { value: '+6', effect: Effect.agility },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Sovereign Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.strength },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Shifting Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.agility },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Sovereign Twilight Opal',
      stats: [
        { value: '+8', effect: Effect.strength },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'World Drop',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Shifting Twilight Opal',
      stats: [
        { value: '+8', effect: Effect.agility },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Tiffany Cartier',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Sovereign Dreadstone',
      stats: [
        { value: '+10', effect: Effect.strength },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Shifting Dreadstone',
      stats: [
        { value: '+10', effect: Effect.agility },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Balanced Shadow Crystal',
      stats: [
        { value: '+12', effect: Effect.attackpower },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Tenuous Shadow Crystal',
      stats: [
        { value: '+6', effect: Effect.agility },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Balanced Shadow Crystal',
      stats: [
        { value: '+14', effect: Effect.attackpower },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Tenuous Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.agility },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Balanced Twilight Opal',
      stats: [
        { value: '+16', effect: Effect.attackpower },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Tenuous Twilight Opal',
      stats: [
        { value: '+8', effect: Effect.agility },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'World Drop',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Balanced Dreadstone',
      stats: [
        { value: '+20', effect: Effect.attackpower },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Tenuous Dreadstone',
      stats: [
        { value: '+10', effect: Effect.agility },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Puissant Shadow Crystal',
      stats: [
        { value: '+6', effect: Effect.armpen },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Infused Shadow Crystal',
      stats: [
        { value: '+12', effect: Effect.attackpower },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Puissant Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.armpen },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Infused Shadow Crystal',
      stats: [
        { value: '+14', effect: Effect.attackpower },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Puissant Twilight Opal',
      stats: [
        { value: '+8', effect: Effect.armpen },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Tiffany Cartier',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Infused Twilight Opal',
      stats: [
        { value: '+16', effect: Effect.attackpower },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: "Anub'arak",
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Puissant Dreadstone',
      stats: [
        { value: '+10', effect: Effect.armpen },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Infused Dreadstone',
      stats: [
        { value: '+20', effect: Effect.attackpower },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: "Guardian's Shadow Crystal",
      stats: [
        { value: '+6', effect: Effect.expertise },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Royal Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+3', effect: Effect.mp5 },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: "Perfect Guardian's Shadow Crystal",
      stats: [
        { value: '+7', effect: Effect.expertise },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Royal Shadow Crystal',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: "Guardian's Twilight Opal",
      stats: [
        { value: '+8', effect: Effect.expertise },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Argent Crusade',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Royal Twilight Opal',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+4', effect: Effect.mp5 },
      ],
      source: 'Tiffany Cartier',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: "Guardian's Dreadstone",
      stats: [
        { value: '+10', effect: Effect.expertise },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Royal Dreadstone',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+5', effect: Effect.mp5 },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: "Defender's Shadow Crystal",
      stats: [
        { value: '+6', effect: Effect.parry },
        { value: '+9', effect: Effect.stamina },
      ],
      source: "Kalu'ak",
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Glowing Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: "Perfect Defender's Shadow Crystal",
      stats: [
        { value: '+7', effect: Effect.parry },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Glowing Shadow Crystal',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: "Defender's Twilight Opal",
      stats: [
        { value: '+8', effect: Effect.parry },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Storm Peaks iron dwarves',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Glowing Twilight Opal',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Knights of the Ebon Blade',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: "Defender's Dreadstone",
      stats: [
        { value: '+10', effect: Effect.parry },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Glowing Dreadstone',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Regal Shadow Crystal',
      stats: [
        { value: '+6', effect: Effect.dodge },
        { value: '+9', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Mysterious Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+8', effect: Effect.spellpen },
      ],
      source: "(A)Captain O'Neal (H)Lady Palanseer",
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Regal Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.dodge },
        { value: '+11', effect: Effect.stamina },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Perfect Mysterious Shadow Crystal',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+9', effect: Effect.spellpen },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Regal Twilight Opal',
      stats: [
        { value: '+8', effect: Effect.dodge },
        { value: '+12', effect: Effect.stamina },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Mysterious Twilight Opal',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+10', effect: Effect.spellpen },
      ],
      source: 'Wintergrasp',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Regal Dreadstone',
      stats: [
        { value: '+10', effect: Effect.dodge },
        { value: '+15', effect: Effect.stamina },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Mysterious Dreadstone',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+13', effect: Effect.spellpen },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
    {
      name: 'Purified Shadow Crystal',
      stats: [
        { value: '+7', effect: Effect.spellpower },
        { value: '+6', effect: Effect.spirit },
      ],
      source: 'Trainer',
      color: Color.purple,
      quality: Quality.uncommon,
    },
    {
      name: 'Perfect Purified Shadow Crystal',
      stats: [
        { value: '+8', effect: Effect.spellpower },
        { value: '+7', effect: Effect.spirit },
      ],
      source: 'Gem Perfection',
      color: Color.purple,
      quality: Quality.perfect,
    },
    {
      name: 'Purified Twilight Opal',
      stats: [
        { value: '+9', effect: Effect.spellpower },
        { value: '+8', effect: Effect.spirit },
      ],
      source: 'World Drop',
      color: Color.purple,
      quality: Quality.rare,
    },
    {
      name: 'Purified Dreadstone',
      stats: [
        { value: '+12', effect: Effect.spellpower },
        { value: '+10', effect: Effect.spirit },
      ],
      source: 'Timothy Jones',
      color: Color.purple,
      quality: Quality.epic,
    },
  ];
  