export type Stats = {
  value: string;
  effect: string;
};

export type GemData = {
  name: string;
  stats: Stats[];
  source: string;
  color: string;
  quality: string;
};

export const gemsData: GemData[] = [
  {
    name: 'Delicate Bloodstone',
    stats: [{ value: '+12', effect: 'Agility' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Runed Bloodstone',
    stats: [{ value: '+14', effect: 'Spell Power' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Delicate Bloodstone',
    stats: [{ value: '+14', effect: 'Agility' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Perfect Runed Bloodstone',
    stats: [{ value: '+16', effect: 'Spell Power' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Delicate Scarlet Ruby',
    stats: [{ value: '+16', effect: 'Agility' }],
    source: 'Tiffany Cartier',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Runed Scarlet Ruby',
    stats: [{ value: '+19', effect: 'Spell Power' }],
    source: 'Kirin Tor',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Delicate Stormjewel',
    stats: [{ value: '+20', effect: 'Agility' }],
    source: 'Bag of Fishing Treasures',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Runed Stormjewel',
    stats: [{ value: '+23', effect: 'Spell Power' }],
    source: 'Bag of Fishing Treasures',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Delicate Cardinal Ruby',
    stats: [{ value: '+20', effect: 'Agility' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Runed Cardinal Ruby',
    stats: [{ value: '+23', effect: 'Spell Power' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Bold Bloodstone',
    stats: [{ value: '+12', effect: 'Strength' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Precise Bloodstone',
    stats: [{ value: '+12', effect: 'Expertise Rating' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Bold Bloodstone',
    stats: [{ value: '+14', effect: 'Strength' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Perfect Precise Bloodstone',
    stats: [{ value: '+14', effect: 'Expertise Rating' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Bold Scarlet Ruby',
    stats: [{ value: '+16', effect: 'Strength' }],
    source: 'Tiffany Cartier',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Precise Scarlet Ruby',
    stats: [{ value: '+16', effect: 'Expertise Rating' }],
    source: 'Herald Volazj',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Bold Stormjewel',
    stats: [{ value: '+20', effect: 'Strength' }],
    source: 'Bag of Fishing Treasures',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Precise Cardinal Ruby',
    stats: [{ value: '+20', effect: 'Expertise Rating' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Bold Cardinal Ruby',
    stats: [{ value: '+20', effect: 'Strength' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Bright Bloodstone',
    stats: [{ value: '+24', effect: 'Attack Power' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Fractured Bloodstone',
    stats: [{ value: '+12', effect: 'Armor Penetration Rating' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Bright Bloodstone',
    stats: [{ value: '+26', effect: 'Attack Power' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Perfect Fractured Bloodstone',
    stats: [{ value: '+14', effect: 'Armor Penetration Rating' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Bright Scarlet Ruby',
    stats: [{ value: '+32', effect: 'Attack Power' }],
    source: 'Trainer',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Fractured Scarlet Ruby',
    stats: [{ value: '+16', effect: 'Armor Penetration Rating' }],
    source: "Nascent Val'kyr",
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Bright Cardinal Ruby',
    stats: [{ value: '+40', effect: 'Attack Power' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Fractured Cardinal Ruby',
    stats: [{ value: '+20', effect: 'Armor Penetration Rating' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Subtle Bloodstone',
    stats: [{ value: '+12', effect: 'Dodge Rating' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Flashing Bloodstone',
    stats: [{ value: '+12', effect: 'Parry Rating' }],
    source: 'Trainer',
    color: 'red',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Subtle Bloodstone',
    stats: [{ value: '+14', effect: 'dodge Rating' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Perfect Flashing Bloodstone',
    stats: [{ value: '+14', effect: 'Parry Rating' }],
    source: 'Gem Perfection',
    color: 'red',
    quality: 'perfect',
  },
  {
    name: 'Subtle Scarlet Ruby',
    stats: [{ value: '+16', effect: 'dodge Rating' }],
    source: 'Tiffany Cartier',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Flashing Scarlet Ruby',
    stats: [{ value: '+16', effect: 'Parry Rating' }],
    source: 'Tiffany Cartier',
    color: 'red',
    quality: 'rare',
  },
  {
    name: 'Subtle Cardinal Ruby',
    stats: [{ value: '+20', effect: 'dodge Rating' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Flashing Cardinal Ruby',
    stats: [{ value: '+20', effect: 'Parry Rating' }],
    source: 'Timothy Jones',
    color: 'red',
    quality: 'epic',
  },
  {
    name: 'Quick Sun Crystal',
    stats: [{ value: '+12', effect: 'Haste Rating' }],
    source: 'Trainer',
    color: 'yellow',
    quality: 'uncommon',
  },
  {
    name: 'Smooth Sun Crystal',
    stats: [{ value: '+12', effect: 'Critical Strike Rating' }],
    source: 'Trainer',
    color: 'yellow',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Quick Sun Crystal',
    stats: [{ value: '+14', effect: 'Haste Rating' }],
    source: 'Gem Perfection',
    color: 'yellow',
    quality: 'perfect',
  },
  {
    name: 'Perfect Smooth Sun Crystal',
    stats: [{ value: '+14', effect: 'Critical Strike Rating' }],
    source: 'Gem Perfection',
    color: 'yellow',
    quality: 'perfect',
  },
  {
    name: "Quick Autumn's Glow",
    stats: [{ value: '+16', effect: 'Haste Rating' }],
    source: 'Tiffany Cartier',
    color: 'yellow',
    quality: 'rare',
  },
  {
    name: "Smooth Autumn's Glow",
    stats: [{ value: '+16', effect: 'Critical Strike Rating' }],
    source: 'Sons of Hodir',
    color: 'yellow',
    quality: 'rare',
  },
  {
    name: "Quick King's Amber",
    stats: [{ value: '+20', effect: 'Haste Rating' }],
    source: 'Timothy Jones',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: "Smooth King's Amber",
    stats: [{ value: '+20', effect: 'Critical Strike Rating' }],
    source: 'Timothy Jones',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: 'Brilliant Sun Crystal',
    stats: [{ value: '+12', effect: 'Intellect' }],
    source: 'Trainer',
    color: 'yellow',
    quality: 'uncommon',
  },
  {
    name: 'Thick Sun Crystal',
    stats: [{ value: '+12', effect: 'Defense Rating' }],
    source: 'Trainer',
    color: 'yellow',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Brilliant Sun Crystal',
    stats: [{ value: '+14', effect: 'Intellect' }],
    source: 'Gem Perfection',
    color: 'yellow',
    quality: 'perfect',
  },
  {
    name: 'Perfect Thick Sun Crystal',
    stats: [{ value: '+14', effect: 'Defense Rating' }],
    source: 'Gem Perfection',
    color: 'yellow',
    quality: 'perfect',
  },
  {
    name: "Brilliant Autumn's Glow",
    stats: [{ value: '+16', effect: 'Intellect' }],
    source: 'Trainer',
    color: 'yellow',
    quality: 'rare',
  },
  {
    name: "Thick Autumn's Glow",
    stats: [{ value: '+16', effect: 'Defense Rating' }],
    source: 'Cyanigosa',
    color: 'yellow',
    quality: 'rare',
  },
  {
    name: 'Brilliant Stormjewel',
    stats: [{ value: '+20', effect: 'Intellect' }],
    source: 'Bag of Fishing Treasures',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: "Thick King's Amber",
    stats: [{ value: '+20', effect: 'Defense Rating' }],
    source: 'Timothy Jones',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: "Brilliant King's Amber",
    stats: [{ value: '+20', effect: 'Intellect' }],
    source: 'Timothy Jones',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: 'Mystic Sun Crystal',
    stats: [{ value: '+12', effect: 'Resilience Rating' }],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'yellow',
    quality: 'uncommon',
  },
  {
    name: 'Rigid Sun Crystal',
    stats: [{ value: '+12', effect: 'Hit Rating' }],
    source: 'Trainer',
    color: 'yellow',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Mystic Sun Crystal',
    stats: [{ value: '+14', effect: 'Resilience Rating' }],
    source: 'Gem Perfection',
    color: 'yellow',
    quality: 'perfect',
  },
  {
    name: 'Perfect Rigid Sun Crystal',
    stats: [{ value: '+14', effect: 'Hit Rating' }],
    source: 'Gem Perfection',
    color: 'yellow',
    quality: 'perfect',
  },
  {
    name: "Mystic Autumn's Glow",
    stats: [{ value: '+16', effect: 'Resilience Rating' }],
    source: 'Wintergrasp',
    color: 'yellow',
    quality: 'rare',
  },
  {
    name: "Rigid Autumn's Glow",
    stats: [{ value: '+16', effect: 'Hit Rating' }],
    source: 'Tiffany Cartier',
    color: 'yellow',
    quality: 'rare',
  },
  {
    name: "Kharmaa's Grace",
    stats: [{ value: '+20', effect: 'Resilience Rating' }],
    source: 'Wintergrasp',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: 'Rigid Stormjewel',
    stats: [{ value: '+20', effect: 'Hit Rating' }],
    source: 'Bag of Fishing Treasures',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: "Mystic King's Amber",
    stats: [{ value: '+20', effect: 'Resilience Rating' }],
    source: 'Timothy Jones',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: "Rigid King's Amber",
    stats: [{ value: '+20', effect: 'Hit Rating' }],
    source: 'Timothy Jones',
    color: 'yellow',
    quality: 'epic',
  },
  {
    name: 'Solid Chalcedony',
    stats: [{ value: '+18', effect: 'Stamina' }],
    source: 'Trainer',
    color: 'blue',
    quality: 'uncommon',
  },
  {
    name: 'Sparkling Chalcedony',
    stats: [{ value: '+12', effect: 'Spirit' }],
    source: 'Trainer',
    color: 'blue',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Solid Chalcedony',
    stats: [{ value: '+21', effect: 'Stamina' }],
    source: 'Gem Perfection',
    color: 'blue',
    quality: 'perfect',
  },
  {
    name: 'Perfect Sparkling Chalcedony',
    stats: [{ value: '+14', effect: 'Spirit' }],
    source: 'Gem Perfection',
    color: 'blue',
    quality: 'perfect',
  },
  {
    name: 'Solid Sky Sapphire',
    stats: [{ value: '+24', effect: 'Stamina' }],
    source: 'Tiffany Cartier',
    color: 'blue',
    quality: 'rare',
  },
  {
    name: 'Sparkling Sky Sapphire',
    stats: [{ value: '+16', effect: 'Spirit' }],
    source: 'Trainer',
    color: 'blue',
    quality: 'rare',
  },
  {
    name: 'Solid Stormjewel',
    stats: [{ value: '+30', effect: 'Stamina' }],
    source: 'Bag of Fishing Treasures',
    color: 'blue',
    quality: 'epic',
  },
  {
    name: 'Sparkling Stormjewel',
    stats: [{ value: '+20', effect: 'Spirit' }],
    source: 'Bag of Fishing Treasures',
    color: 'blue',
    quality: 'epic',
  },
  {
    name: 'Solid Majestic Zircon',
    stats: [{ value: '+30', effect: 'Stamina' }],
    source: 'Timothy Jones',
    color: 'blue',
    quality: 'epic',
  },
  {
    name: 'Sparkling Majestic Zircon',
    stats: [{ value: '+20', effect: 'Spirit' }],
    source: 'Timothy Jones',
    color: 'blue',
    quality: 'epic',
  },
  {
    name: 'Lustrous Chalcedony',
    stats: [{ value: '+6', effect: 'Mp5' }],
    source: 'Trainer',
    color: 'blue',
    quality: 'uncommon',
  },
  {
    name: 'Stormy Chalcedony',
    stats: [{ value: '+15', effect: 'Spell Penetration' }],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'blue',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Lustrous Chalcedony',
    stats: [{ value: '+7', effect: 'Mp5' }],
    source: 'Gem Perfection',
    color: 'blue',
    quality: 'perfect',
  },
  {
    name: 'Perfect Stormy Chalcedony',
    stats: [{ value: '+18', effect: 'Spell Penetration' }],
    source: 'Gem Perfection',
    color: 'blue',
    quality: 'perfect',
  },
  {
    name: 'Lustrous Sky Sapphire',
    stats: [{ value: '+8', effect: 'Mp5' }],
    source: 'Tiffany Cartier',
    color: 'blue',
    quality: 'rare',
  },
  {
    name: 'Stormy Sky Sapphire',
    stats: [{ value: '+20', effect: 'Spell Penetration' }],
    source: 'Wintergrasp',
    color: 'blue',
    quality: 'rare',
  },
  {
    name: 'Lustrous Majestic Zircon',
    stats: [{ value: '+10', effect: 'Mp5' }],
    source: 'Timothy Jones',
    color: 'blue',
    quality: 'epic',
  },
  {
    name: 'Stormy Majestic Zircon',
    stats: [{ value: '+25', effect: 'Spell Penetration' }],
    source: 'Timothy Jones',
    color: 'blue',
    quality: 'epic',
  },
  {
    name: 'Durable Huge Citrine',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+6', effect: 'Resilience Rating' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Stark Huge Citrine',
    stats: [
      { value: '+12', effect: 'Attack Power' },
      { value: '+6', effect: 'Haste Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Durable Huge Citrine',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+7', effect: 'Resilience Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Stark Huge Citrine',
    stats: [
      { value: '+14', effect: 'Attack Power' },
      { value: '+7', effect: 'Haste Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Durable Monarch Topaz',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+8', effect: 'Resilience Rating' },
    ],
    source: 'Wintergrasp',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Stark Monarch Topaz',
    stats: [
      { value: '+16', effect: 'Attack Power' },
      { value: '+8', effect: 'Haste Rating' },
    ],
    source: 'Tiffany Cartier',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Durable Ametrine',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+10', effect: 'Resilience Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Stark Ametrine',
    stats: [
      { value: '+20', effect: 'Attack Power' },
      { value: '+10', effect: 'Haste Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Luminous Huge Citrine',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+6', effect: 'Intellect' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Pristine Huge Citrine',
    stats: [
      { value: '+12', effect: 'Attack Power' },
      { value: '+6', effect: 'Hit Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Luminous Huge Citrine',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+7', effect: 'Intellect' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Pristine Huge Citrine',
    stats: [
      { value: '+14', effect: 'Attack Power' },
      { value: '+7', effect: 'Hit Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Luminous Monarch Topaz',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+8', effect: 'Intellect' },
    ],
    source: 'Tiffany Cartier',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Pristine Monarch Topaz',
    stats: [
      { value: '+16', effect: 'Attack Power' },
      { value: '+8', effect: 'Hit Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Luminous Ametrine',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+10', effect: 'Intellect' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Pristine Ametrine',
    stats: [
      { value: '+20', effect: 'Attack Power' },
      { value: '+10', effect: 'Hit Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Potent Huge Citrine',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+7', effect: 'Critical Strike Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Wicked Huge Citrine',
    stats: [
      { value: '+12', effect: 'Attack Power' },
      { value: '+6', effect: 'Critical Strike Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Potent Huge Citrine',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+6', effect: 'Critical Strike Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Wicked Huge Citrine',
    stats: [
      { value: '+14', effect: 'Attack Power' },
      { value: '+7', effect: 'Critical Strike Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Potent Monarch Topaz',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+8', effect: 'Critical Strike Rating' },
    ],
    source: 'Tiffany Cartier',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Wicked Monarch Topaz',
    stats: [
      { value: '+16', effect: 'Attack Power' },
      { value: '+8', effect: 'Critical Strike Rating' },
    ],
    source: 'Knights of the Ebon Blade',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Potent Ametrine',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+10', effect: 'Critical Strike Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Wicked Ametrine',
    stats: [
      { value: '+20', effect: 'Attack Power' },
      { value: '+10', effect: 'Critical Strike Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Veiled Huge Citrine',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+6', effect: 'Hit Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Empowered Huge Citrine',
    stats: [
      { value: '+12', effect: 'Attack Power' },
      { value: '+6', effect: 'Resilience Rating' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Veiled Huge Citrine',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+7', effect: 'Hit Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Empowered Huge Citrine',
    stats: [
      { value: '+14', effect: 'Attack Power' },
      { value: '+7', effect: 'Resilience Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Veiled Monarch Topaz',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+8', effect: 'Hit Rating' },
    ],
    source: 'Tiffany Cartier',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Empowered Monarch Topaz',
    stats: [
      { value: '+16', effect: 'Attack Power' },
      { value: '+8', effect: 'Resilience Rating' },
    ],
    source: 'Wintergrasp',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Veiled Ametrine',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+10', effect: 'Hit Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Empowered Ametrine',
    stats: [
      { value: '+20', effect: 'Attack Power' },
      { value: '+10', effect: 'Resilience Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Reckless Huge Citrine',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+6', effect: 'Haste Rating' },
    ],
    source: 'Frenzyheart',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Deft Huge Citrine',
    stats: [
      { value: '+6', effect: 'Agility' },
      { value: '+6', effect: 'Haste Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Reckless Huge Citrine',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+7', effect: 'Haste Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Deft Huge Citrine',
    stats: [
      { value: '+7', effect: 'Agility' },
      { value: '+7', effect: 'HasteRating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Reckless Monarch Topaz',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+8', effect: 'Haste Rating' },
    ],
    source: 'Tiffany Cartier',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Deft Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Agility' },
      { value: '+8', effect: 'Haste Rating' },
    ],
    source: 'Sjonnir the Ironshaper',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Reckless Ametrine',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+10', effect: 'Haste Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Deft Ametrine',
    stats: [
      { value: '+10', effect: 'Agility' },
      { value: '+10', effect: 'Haste Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Inscribed Huge Citrine',
    stats: [
      { value: '+6', effect: 'Strength' },
      { value: '+6', effect: 'Critical Strike Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Glinting Huge Citrine',
    stats: [
      { value: '+6', effect: 'Agility' },
      { value: '+6', effect: 'Hit Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Inscribed Huge Citrine',
    stats: [
      { value: '+7', effect: 'Strength' },
      { value: '+7', effect: 'Critical Strike Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Glinting Huge Citrine',
    stats: [
      { value: '+7', effect: 'Agility' },
      { value: '+7', effect: 'Hit Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Inscribed Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Strength' },
      { value: '+8', effect: 'Critical Strike Rating' },
    ],
    source: 'World Drop',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Glinting Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Agility' },
      { value: '+8', effect: 'Hit Rating' },
    ],
    source: 'Tiffany Cartier',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Inscribed Ametrine',
    stats: [
      { value: '+10', effect: 'Strength' },
      { value: '+10', effect: 'Critical Strike Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Glinting Ametrine',
    stats: [
      { value: '+10', effect: 'Agility' },
      { value: '+10', effect: 'Hit Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Etched Huge Citrine',
    stats: [
      { value: '+6', effect: 'Strength' },
      { value: '+6', effect: 'Hit Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Deadly Huge Citrine',
    stats: [
      { value: '+6', effect: 'Agility' },
      { value: '+6', effect: 'Critical Strike Rating' },
    ],
    source: 'Knights of the Ebon Blade',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Etched Huge Citrine',
    stats: [
      { value: '+7', effect: 'Strength' },
      { value: '+7', effect: 'Hit Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Deadly Huge Citrine',
    stats: [
      { value: '+7', effect: 'Agility' },
      { value: '+7', effect: 'Critical Strike Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Etched Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Strength' },
      { value: '+8', effect: 'Hit Rating' },
    ],
    source: 'World Drop',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Deadly Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Agility' },
      { value: '+8', effect: 'Critical Strike Rating' },
    ],
    source: 'Keristrasza',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Etched Ametrine',
    stats: [
      { value: '+10', effect: 'Strength' },
      { value: '+10', effect: 'Hit Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Deadly Ametrine',
    stats: [
      { value: '+10', effect: 'Agility' },
      { value: '+10', effect: 'Critical Strike Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Fierce Huge Citrine',
    stats: [
      { value: '+6', effect: 'Strength' },
      { value: '+6', effect: 'Haste Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Lucent Huge Citrine',
    stats: [
      { value: '+6', effect: 'Agility' },
      { value: '+6', effect: 'Resilience Rating' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Fierce Huge Citrine',
    stats: [
      { value: '+7', effect: 'Strength' },
      { value: '+7', effect: 'Haste Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Lucent Huge Citrine',
    stats: [
      { value: '+7', effect: 'Agility' },
      { value: '+7', effect: 'Resilience Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Fierce Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Strength' },
      { value: '+8', effect: 'Haste Rating' },
    ],
    source: 'Ingvar the Plunderer',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Lucent Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Agility' },
      { value: '+8', effect: 'Resilience Rating' },
    ],
    source: 'Wintergrasp',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Fierce Ametrine',
    stats: [
      { value: '+10', effect: 'Strength' },
      { value: '+10', effect: 'Haste Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Lucent Ametrine',
    stats: [
      { value: '+10', effect: 'Agility' },
      { value: '+10', effect: 'Resilience Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Resplendent Huge Citrine',
    stats: [
      { value: '+6', effect: 'Strength' },
      { value: '+6', effect: 'Resilience Rating' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Stalwart Huge Citrine',
    stats: [
      { value: '+6', effect: 'Dodge' },
      { value: '+6', effect: 'Defense Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Resplendent Huge Citrine',
    stats: [
      { value: '+7', effect: 'Strength' },
      { value: '+7', effect: 'Resilience Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Stalwart Huge Citrine',
    stats: [
      { value: '+7', effect: 'Dodge' },
      { value: '+7', effect: 'Defense Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Resplendent Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Strength' },
      { value: '+8', effect: 'Resilience Rating' },
    ],
    source: 'Wintergrasp',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Stalwart Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Dodge' },
      { value: '+8', effect: 'Defense Rating' },
    ],
    source: 'World Drop',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Resplendent Ametrine',
    stats: [
      { value: '+10', effect: 'Strength' },
      { value: '+10', effect: 'Resilience Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Stalwart Ametrine',
    stats: [
      { value: '+10', effect: 'Dodge' },
      { value: '+10', effect: 'Defense Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: "Champion's Huge Citrine",
    stats: [
      { value: '+6', effect: 'Strength' },
      { value: '+6', effect: 'Defense Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Glimmering Huge Citrine',
    stats: [
      { value: '+6', effect: 'Parry' },
      { value: '+6', effect: 'Defense Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: "Perfect Champion's Huge Citrine",
    stats: [
      { value: '+7', effect: 'Strength' },
      { value: '+7', effect: 'Defense Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Glimmering Huge Citrine',
    stats: [
      { value: '+7', effect: 'Parry' },
      { value: '+7', effect: 'Defense Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: "Champion's Monarch Topaz",
    stats: [
      { value: '+8', effect: 'Strength' },
      { value: '+8', effect: 'Defense Rating' },
    ],
    source: 'World Drop',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Glimmering Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Parry' },
      { value: '+8', effect: 'Defense Rating' },
    ],
    source: 'Wyrmrest Accord',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: "Champion's Ametrine",
    stats: [
      { value: '+10', effect: 'Strength' },
      { value: '+10', effect: 'Defense Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Glimmering Ametrine',
    stats: [
      { value: '+10', effect: 'Parry' },
      { value: '+10', effect: 'Defense Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Accurate Huge Citrine',
    stats: [
      { value: '+6', effect: 'Expertise Rating' },
      { value: '+6', effect: 'Hit Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Resolute Huge Citrine',
    stats: [
      { value: '+6', effect: 'Expertise Rating' },
      { value: '+6', effect: 'Defense Rating' },
    ],
    source: 'Trainer',
    color: 'orange',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Accurate Huge Citrine',
    stats: [
      { value: '+7', effect: 'Expertise Rating' },
      { value: '+7', effect: 'Hit Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Perfect Resolute Huge Citrine',
    stats: [
      { value: '+7', effect: 'Expertise Rating' },
      { value: '+7', effect: 'Defense Rating' },
    ],
    source: 'Gem Perfection',
    color: 'orange',
    quality: 'perfect',
  },
  {
    name: 'Accurate Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Expertise Rating' },
      { value: '+8', effect: 'Hit Rating' },
    ],
    source: 'Storm Peaks mammoths',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Resolute Monarch Topaz',
    stats: [
      { value: '+8', effect: 'Expertise Rating' },
      { value: '+8', effect: 'Defense Rating' },
    ],
    source: 'World Drop',
    color: 'orange',
    quality: 'rare',
  },
  {
    name: 'Accurate Ametrine',
    stats: [
      { value: '+10', effect: 'Expertise Rating' },
      { value: '+10', effect: 'Hit Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Resolute Ametrine',
    stats: [
      { value: '+10', effect: 'Expertise Rating' },
      { value: '+10', effect: 'Defense Rating' },
    ],
    source: 'Timothy Jones',
    color: 'orange',
    quality: 'epic',
  },
  {
    name: 'Jagged Dark Jade',
    stats: [
      { value: '+6', effect: 'Critical Strike Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Opaque Dark Jade',
    stats: [
      { value: '+6', effect: 'Resilience Rating' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Jagged Dark Jade',
    stats: [
      { value: '+7', effect: 'Critical Strike Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Opaque Dark Jade',
    stats: [
      { value: '+7', effect: 'Resilience Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Jagged Forest Emerald',
    stats: [
      { value: '+8', effect: 'Critical Strike Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Frenzyheart',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Opaque Forest Emerald',
    stats: [
      { value: '+8', effect: 'Resilience Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Wintergrasp',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Jagged Eye of Zul',
    stats: [
      { value: '+10', effect: 'Critical Strike Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Opaque Eye of Zul',
    stats: [
      { value: '+10', effect: 'Resilience Rating' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Forceful Dark Jade',
    stats: [
      { value: '+', effect: '6 Haste Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Dazzling Dark Jade',
    stats: [
      { value: '+6', effect: 'Intellect' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Forceful Dark Jade',
    stats: [
      { value: '+7', effect: 'Haste Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Dazzling Dark Jade',
    stats: [
      { value: '+7', effect: 'Intellect' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Forceful Forest Emerald',
    stats: [
      { value: '+8', effect: 'Haste Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Dazzling Forest Emerald',
    stats: [
      { value: '+8', effect: 'Intellect' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Forceful Eye of Zul',
    stats: [
      { value: '+10', effect: 'Haste Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Dazzling Eye of Zul',
    stats: [
      { value: '+10', effect: 'Intellect' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Enduring Dark Jade',
    stats: [
      { value: '+6', effect: 'Defense Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Sundered Dark Jade',
    stats: [
      { value: '+6', effect: 'Critical Strike Rating' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Enduring Dark Jade',
    stats: [
      { value: '+7', effect: 'Defense Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Sundered Dark Jade',
    stats: [
      { value: '+7', effect: 'Critical Strike Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Enduring Forest Emerald',
    stats: [
      { value: '+8', effect: 'Defense Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Sundered Forest Emerald',
    stats: [
      { value: '+8', effect: 'Critical Strike Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Oracles',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Enduring Eye of Zul',
    stats: [
      { value: '+10', effect: 'Defense Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Sundered Eye of Zul',
    stats: [
      { value: '+10', effect: 'Critical Strike Rating' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Timeless Dark Jade',
    stats: [
      { value: '+6', effect: 'Intellect' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Lambent Dark Jade',
    stats: [
      { value: '+6', effect: 'Hit Rating' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Timeless Dark Jade',
    stats: [
      { value: '+7', effect: 'Intellect' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Lambent Dark Jade',
    stats: [
      { value: '+7', effect: 'Hit Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Timeless Forest Emerald',
    stats: [
      { value: '+8', effect: 'Intellect' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: "The Prophet Tharon'ja",
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Lambent Forest Emerald',
    stats: [
      { value: '+8', effect: 'Hit Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Timeless Eye of Zul',
    stats: [
      { value: '+10', effect: 'Intellect' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Lambent Eye of Zul',
    stats: [
      { value: '+10', effect: 'Hit Rating' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Vivid Dark Jade',
    stats: [
      { value: '+6', effect: 'Hit Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Oracles',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Energized Dark Jade',
    stats: [
      { value: '+6', effect: 'Haste Rating' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Vivid Dark Jade',
    stats: [
      { value: '+7', effect: 'Hit Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Energized Dark Jade',
    stats: [
      { value: '+7', effect: 'Haste Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Vivid Forest Emerald',
    stats: [
      { value: '+8', effect: 'Hit Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Energized Forest Emerald',
    stats: [
      { value: '+8', effect: 'Haste Rating' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Vivid Eye of Zul',
    stats: [
      { value: '+10', effect: 'Hit Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Energized Eye of Zul',
    stats: [
      { value: '+10', effect: 'Haste Rating' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Steady Dark Jade',
    stats: [
      { value: '+6', effect: 'Resilience Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Intricate Dark Jade',
    stats: [
      { value: '+6', effect: 'Haste Rating' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Steady Dark Jade',
    stats: [
      { value: '+7', effect: 'Resilience Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Intricate Dark Jade',
    stats: [
      { value: '+7', effect: 'Haste Rating' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Steady Forest Emerald',
    stats: [
      { value: '+8', effect: 'Resilience Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Wintergrasp',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Intricate Forest Emerald',
    stats: [
      { value: '+8', effect: 'Haste Rating' },
      { value: '+8', effect: 'Spirit' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Steady Eye of Zul',
    stats: [
      { value: '+10', effect: 'Resilience Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Intricate Eye of Zul',
    stats: [
      { value: '+10', effect: 'Haste Rating' },
      { value: '+10', effect: 'Spirit' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Radiant Dark Jade',
    stats: [
      { value: '+6', effect: 'Critical Strike Rating' },
      { value: '+8', effect: 'Spell Penetration' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: "Seer's Dark Jade",
    stats: [
      { value: '+6', effect: 'Intellect' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: "Kalu'ak",
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Radiant Dark Jade',
    stats: [
      { value: '+7', effect: 'Critical Strike Rating' },
      { value: '+9', effect: 'Spell Penetration' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: "Perfect Seer's Dark Jade",
    stats: [
      { value: '+7', effect: 'Intellect' },
      { value: '+7', effect: 'Spirit' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Radiant Forest Emerald',
    stats: [
      { value: '+8', effect: 'Critical Strike Rating' },
      { value: '+10', effect: 'Spell Penetration' },
    ],
    source: 'Storm Peaks harpies',
    color: 'green',
    quality: 'rare',
  },
  {
    name: "Seer's Forest Emerald",
    stats: [
      { value: '+8', effect: 'Intellect' },
      { value: '+8', effect: 'Spirit' },
    ],
    source: 'Tiffany Cartier',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Radiant Eye of Zul',
    stats: [
      { value: '+10', effect: 'Critical Strike Rating' },
      { value: '+13', effect: 'Spell Penetration' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: "Seer's Eye of Zul",
    stats: [
      { value: '+10', effect: 'Intellect' },
      { value: '+10', effect: 'Spirit' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Tense Dark Jade',
    stats: [
      { value: '+6', effect: 'Hit Rating' },
      { value: '+8', effect: 'Spell Penetration' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Shining Dark Jade',
    stats: [
      { value: '+6', effect: 'Hit Rating' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Tense Dark Jade',
    stats: [
      { value: '+6', effect: 'Hit Rating' },
      { value: '+9', effect: 'Spell Penetration' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Shining Dark Jade',
    stats: [
      { value: '+7', effect: 'Hit Rating' },
      { value: '+7', effect: 'Spirit' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Tense Forest Emerald',
    stats: [
      { value: '+6', effect: 'Hit Rating' },
      { value: '+10', effect: 'Spell Penetration' },
    ],
    source: 'Wintergrasp',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Shining Forest Emerald',
    stats: [
      { value: '+8', effect: 'Hit Rating' },
      { value: '+8', effect: 'Spirit' },
    ],
    source: 'World Drop',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Tense Eye of Zul',
    stats: [
      { value: '+10', effect: 'Hit Rating' },
      { value: '+13', effect: 'Spell Penetration' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Shining Eye of Zul',
    stats: [
      { value: '+10', effect: 'Hit Rating' },
      { value: '+10', effect: 'Spirit' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Shattered Dark Jade',
    stats: [
      { value: '+6', effect: 'Haste Rating' },
      { value: '+8', effect: 'Spell Penetration' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Misty Dark Jade',
    stats: [
      { value: '+6', effect: 'Critical Strike Rating' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: 'Trainer',
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Shattered Dark Jade',
    stats: [
      { value: '+7', effect: 'Haste Rating' },
      { value: '+9', effect: 'Spell Penetration' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Perfect Misty Dark Jade',
    stats: [
      { value: '+7', effect: 'Critical Strike Rating' },
      { value: '+7', effect: 'Spirit' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Shattered Forest Emerald',
    stats: [
      { value: '+8', effect: 'Haste Rating' },
      { value: '+10', effect: 'Spell Penetration' },
    ],
    source: 'Wintergrasp',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Misty Forest Emerald',
    stats: [
      { value: '+8', effect: 'Critical Strike Rating' },
      { value: '+8', effect: 'Spirit' },
    ],
    source: 'World Drop',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Shattered Eye of Zul',
    stats: [
      { value: '+10', effect: 'Haste Rating' },
      { value: '+13', effect: 'Spell Penetration' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Misty Eye of Zul',
    stats: [
      { value: '+10', effect: 'Critical Strike Rating' },
      { value: '+10', effect: 'Spirit' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Turbid Dark Jade',
    stats: [
      { value: '+6', effect: 'Resilience Rating' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'green',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Turbid Dark Jade',
    stats: [
      { value: '+7', effect: 'Resilience Rating' },
      { value: '+7', effect: 'Spirit' },
    ],
    source: 'Gem Perfection',
    color: 'green',
    quality: 'perfect',
  },
  {
    name: 'Turbid Forest Emerald',
    stats: [
      { value: '+8', effect: 'Resilience Rating' },
      { value: '+8', effect: 'Spirit' },
    ],
    source: 'Wintergrasp',
    color: 'green',
    quality: 'rare',
  },
  {
    name: 'Turbid Eye of Zul',
    stats: [
      { value: '+10', effect: 'Resilience Rating' },
      { value: '+10', effect: 'Spirit' },
    ],
    source: 'Timothy Jones',
    color: 'green',
    quality: 'epic',
  },
  {
    name: 'Sovereign Shadow Crystal',
    stats: [
      { value: '+6', effect: 'Strength' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Shifting Shadow Crystal',
    stats: [
      { value: '+6', effect: 'Agility' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Sovereign Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Strength' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Perfect Shifting Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Agility' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Sovereign Twilight Opal',
    stats: [
      { value: '+8', effect: 'Strength' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'World Drop',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Shifting Twilight Opal',
    stats: [
      { value: '+8', effect: 'Agility' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Tiffany Cartier',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Sovereign Dreadstone',
    stats: [
      { value: '+10', effect: 'Strength' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Shifting Dreadstone',
    stats: [
      { value: '+10', effect: 'Agility' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Balanced Shadow Crystal',
    stats: [
      { value: '+12', effect: 'Attack Power' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Tenuous Shadow Crystal',
    stats: [
      { value: '+6', effect: 'Agility' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Balanced Shadow Crystal',
    stats: [
      { value: '+14', effect: 'Attack Power' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Perfect Tenuous Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Agility' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Balanced Twilight Opal',
    stats: [
      { value: '+16', effect: 'Attack Power' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Tenuous Twilight Opal',
    stats: [
      { value: '+8', effect: 'Agility' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'World Drop',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Balanced Dreadstone',
    stats: [
      { value: '+20', effect: 'Attack Power' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Tenuous Dreadstone',
    stats: [
      { value: '+10', effect: 'Agility' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Puissant Shadow Crystal',
    stats: [
      { value: '+6', effect: 'Armor Penetration' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Infused Shadow Crystal',
    stats: [
      { value: '+12', effect: 'Attack Power' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Puissant Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Armor Penetration' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Perfect Infused Shadow Crystal',
    stats: [
      { value: '+14', effect: 'Attack Power' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Puissant Twilight Opal',
    stats: [
      { value: '+8', effect: 'Armor Penetration' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Tiffany Cartier',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Infused Twilight Opal',
    stats: [
      { value: '+16', effect: 'Attack Power' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: "Anub'arak",
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Puissant Dreadstone',
    stats: [
      { value: '+10', effect: 'Armor Penetration' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Infused Dreadstone',
    stats: [
      { value: '+20', effect: 'Attack Power' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: "Guardian's Shadow Crystal",
    stats: [
      { value: '+6', effect: 'Expertise Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Royal Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+3', effect: 'Mp5' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: "Perfect Guardian's Shadow Crystal",
    stats: [
      { value: '+7', effect: 'Expertise Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Perfect Royal Shadow Crystal',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: "Guardian's Twilight Opal",
    stats: [
      { value: '+8', effect: 'Expertise Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Argent Crusade',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Royal Twilight Opal',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+4', effect: 'Mp5' },
    ],
    source: 'Tiffany Cartier',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: "Guardian's Dreadstone",
    stats: [
      { value: '+10', effect: 'Expertise Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Royal Dreadstone',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+5', effect: 'Mp5' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: "Defender's Shadow Crystal",
    stats: [
      { value: '+6', effect: 'Parry Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: "Kalu'ak",
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Glowing Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: "Perfect Defender's Shadow Crystal",
    stats: [
      { value: '+7', effect: 'Parry Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Perfect Glowing Shadow Crystal',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: "Defender's Twilight Opal",
    stats: [
      { value: '+8', effect: 'Parry Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Storm Peaks iron dwarves',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Glowing Twilight Opal',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Knights of the Ebon Blade',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: "Defender's Dreadstone",
    stats: [
      { value: '+10', effect: 'Parry Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Glowing Dreadstone',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Regal Shadow Crystal',
    stats: [
      { value: '+6', effect: 'Dodge Rating' },
      { value: '+9', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Mysterious Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+8', effect: 'Spell Penetration' },
    ],
    source: "(A)Captain O'Neal (H)Lady Palanseer",
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Regal Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Dodge Rating' },
      { value: '+11', effect: 'Stamina' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Perfect Mysterious Shadow Crystal',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+9', effect: 'Spell Penetration' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Regal Twilight Opal',
    stats: [
      { value: '+8', effect: 'Dodge Rating' },
      { value: '+12', effect: 'Stamina' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Mysterious Twilight Opal',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+10', effect: 'Spell Penetration' },
    ],
    source: 'Wintergrasp',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Regal Dreadstone',
    stats: [
      { value: '+10', effect: 'Dodge Rating' },
      { value: '+15', effect: 'Stamina' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Mysterious Dreadstone',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+13', effect: 'Spell Penetration' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
  {
    name: 'Purified Shadow Crystal',
    stats: [
      { value: '+7', effect: 'Spell Power' },
      { value: '+6', effect: 'Spirit' },
    ],
    source: 'Trainer',
    color: 'purple',
    quality: 'uncommon',
  },
  {
    name: 'Perfect Purified Shadow Crystal',
    stats: [
      { value: '+8', effect: 'Spell Power' },
      { value: '+7', effect: 'Spirit' },
    ],
    source: 'Gem Perfection',
    color: 'purple',
    quality: 'perfect',
  },
  {
    name: 'Purified Twilight Opal',
    stats: [
      { value: '+9', effect: 'Spell Power' },
      { value: '+8', effect: 'Spirit' },
    ],
    source: 'World Drop',
    color: 'purple',
    quality: 'rare',
  },
  {
    name: 'Purified Dreadstone',
    stats: [
      { value: '+12', effect: 'Spell Power' },
      { value: '+10', effect: 'Spirit' },
    ],
    source: 'Timothy Jones',
    color: 'purple',
    quality: 'epic',
  },
];
